### ISSUE TITLE
Class 'Incursus\LaravelS3Tools\S3ToolsServiceProvider' not found

### ISSUE THREAD

**Issue by DanielHartUK** [sburkett/laravel-s3-tools#1]
- PHP Version: 7.2
- Laravel Version: 5.8
- Laravel-S3-Tools Version: 1.0.0

### Describe the issue
Laravel returns the error `Class 'Incursus\LaravelS3Tools\S3ToolsServiceProvider' not found` once `Incursus\LaravelS3Tools\S3ToolsServiceProvider::class` is added to the providers array in `config/app.php`.

### Steps to reproduce
1. Require the project with `composer require incursus/laravel-s3-tools`
1. Add `Incursus\LaravelS3Tools\S3ToolsServiceProvider::class` to the providers array in `config/app.php`
1. Load any page to encounter the issue.

### Additional context
The necessary env variables and disk configuration in `config/filesystem.php` have been set. I've also tried running `composer dump-autoload` to no avail.

**Comment by sunny047** [comment]
Hi
Any update on this .I am facing same issue.

**Comment by sburkett** [comment]
Wow, for some reason I didn't get a notification on this message. So sorry that it has taken me this long to get to this!

I'll take a look and see what the deal is.

**Comment by hotmeteor** [comment]
Just hit this myself.

**Comment by hotmeteor** [comment]
I think the PSR-4 namespace is wrong in `composer.json`.

**Comment by sburkett** [comment]
You are correct. Not sure really how that happened. It shouldn't be `"Incursus\\laravel-s3-tools\\": "src/"` but `"Incursus\\LaravelS3Tools\\": "src/" I believe. However on a first test it seems to throw the same error. I will look closer when I get back home tonight.

**Comment by sburkett** [comment]
Ok, just implemented a fix for this issue (as release v1.0.1). Thanks for reporting!
