### ISSUE TITLE
Config options not actually being used

### ISSUE THREAD

**Issue by hotmeteor** [sburkett/laravel-s3-tools#3]
- PHP Version: 7.2.22
- Laravel Version: 5.8.x
- Laravel-S3-Tools Version: 1.0.1

### Describe the issue
Filesystem config for the `s3-tools` disk is not actually being on honored in the service provider.

### Steps to reproduce
1. Add config settings, that may or may not use the same `.env` keynames for config settings
2. Attempt to use this library
3. Receive warnings about missing config values

### Additional context
The config values are currently hardcoded into the service provider ([marked as a TODO](https://github.com/sburkett/laravel-s3-tools/blob/master/src/S3ToolsServiceProvider.php#L29)), but should be using the `filesystem` config that docs instructed to add.

**Comment by sburkett** [comment]
Agreed - that is why I put the TODO in there to remind me :) I'll try to get to that as soon as I can.

**Comment by sburkett** [comment]
This should be resolved in the latest release v1.0.2. If you have any issues with it, feel free to reopen!

**Comment by hotmeteor** [comment]
Thanks!

**Comment by hotmeteor** [comment]
1.0.2 doesn't seem to be getting picked up by packagist. Any ideas?
