### ISSUE TITLE
getObjectVersions() method doesn't filter for object

### ISSUE THREAD

**Issue by hotmeteor** [sburkett/laravel-s3-tools#5]
- PHP Version: 7.2.22
- Laravel Version: 5.8.x
- Laravel-S3-Tools Version: 1.0.1

### Describe the issue
The `getObjectVersions($objectPath)` function is intended to return all versions for a specific object, however because it's not using the `Prefix` option it is returning all versions for all objects in the bucket.

### Steps to reproduce
1. Obtain a path for an object in the bucket
2. Use `getObjectVersions($objectPath)` to retrieve the versions
3. Response contains up to 1000 versions from all objects, not just for the specified object

### Additional context
The `getObjectVersions` should be using the `Prefix` option to narrow results just to the specific path.

**Comment by sburkett** [comment]
Thanks! I'll take a peek at it. Probably just an oversight on my part when I first put the package together.

**Comment by hotmeteor** [comment]
I created a PR for it if you’re interested.

**Comment by sburkett** [comment]
Ah, I see now what happened. We store all of our hash prefixes ourselves (split into 4 hex groupings), and use that as the object key when storing or retrieving it to S3. In other words, we don't have a shared prefix common to all objects, or groups of objects (unless there is a hash collision of course). It didn't even occur to me to think about user-defined prefixes. Whoops lol. 

I saw the PR .. thanks much for that! I'll take a peek at it here shortly.

**Comment by sburkett** [comment]
It should already be tagged as `v1.0.2`
